version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=tint
      - POSTGRES_PASSWORD=tint
    volumes:
      - tint-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  tint-pgdata: