version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=tint
      - POSTGRES_PASSWORD=tint
      - POSTGRES_DB=tint
    volumes:
      - ./var/db/00-init-db.sh:/docker-entrypoint-initdb.d/00-init-db.sh
      - type: tmpfs
        target: /var/lib/postgresql/data
    ports:
      - "15432:15432"
